spring:
  application:
    name: export

  config:
    import: optional:classpath:security.yaml

  datasource:
    url: jdbc:sqlite:museum_export.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    hibernate:
      ddl-auto: update