include:
  - backend/infra/minio/docker-compose.yml

services:
  # Entry Point
  api-gateway:
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile
    container_name: museum-gateway
    ports:
      - "8000:8000"
    depends_on:
      - auth-service
      - user-service

  # Services
  auth-service:
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
    container_name: museum-auth
    ports:
      - "8080:8080"
    volumes:
      - ./backend/auth-service/museum_auth.db:/app/museum_auth.db
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JWT_SECRET=${JWT_SECRET}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_BOT_NAME=${TELEGRAM_BOT_NAME}
      - USER_SERVICE_URL=http://user-service:8080
    depends_on:
      - minio

  user-service:
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile
    container_name: museum-user
    ports:
      - "8081:8080"
    volumes:
      - ./backend/user-service/museum_user.db:/app/museum_user.db
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - minio
      - auth-service

  artist-service:
    build:
      context: ./backend/artist-service
      dockerfile: Dockerfile
    container_name: museum-artist
    ports:
      - "8082:8080"
    volumes:
      - ./backend/artist-service/museum_artist.db:/app/museum_artist.db
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JWT_SECRET=${JWT_SECRET}
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
    depends_on:
      - minio
      - auth-service

  art-service:
    build:
      context: ./backend/art-service
      dockerfile: Dockerfile
    container_name: museum-art
    ports:
      - "8083:8080"
    volumes:
      - ./backend/art-service/museum_art.db:/app/museum_art.db
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JWT_SECRET=${JWT_SECRET}
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
    depends_on:
      - minio
      - auth-service

  export-service:
    build:
      context: ./backend/export-service
      dockerfile: Dockerfile
    container_name: museum-export
    ports:
      - "8084:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - auth-service

  notification-service:
    build:
      context: ./backend/notification-service
      dockerfile: Dockerfile
    container_name: museum-notification
    ports:
      - "8086:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JWT_SECRET=${JWT_SECRET}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - TEST_EMAIL_OVERRIDE=${TEST_EMAIL_OVERRIDE}
    depends_on:
      - auth-service

  statistics-service:
    build:
      context: ./backend/statistics-service
      dockerfile: Dockerfile
    container_name: museum-statistics
    ports:
      - "8085:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - auth-service
      - art-service
      - artist-service
  frontend-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: museum-frontend
    ports:
      - "80:80"               # Accessible at http://localhost
    depends_on:
      - auth-service
      - api-gateway
