include:
  - infra/minio/docker-compose.yml

services:
  # Entry Point
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: museum-gateway
    ports:
      - "8000:8000"
    depends_on:
      - auth-service
      - user-service

  # Services
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: museum-auth
    ports:
      - "8080:8080"
    volumes:
      - ./auth-service/museum_auth.db:/app/museum_auth.db
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - minio

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: museum-user
    ports:
      - "8081:8080"
    volumes:
      - ./user-service/museum_user.db:/app/museum_user.db
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - minio
      - auth-service

  # Placeholders for future services
  # art-service:
  #   build: ./art-service
  # artist-service:
  #   build: ./artist-service
