spring:
  application:
    name: auth

  config:
    import: optional:classpath:security.yaml

  datasource:
    url: jdbc:sqlite:museum_auth.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    hibernate:
      ddl-auto: update

services:
  notification:
    url: ${NOTIFICATION_SERVICE_URL:http://notification-service:8080}
  user:
    url: ${USER_SERVICE_URL:http://user-service:8080}
