server:
  port: 8000

spring:
  application:
    name: api-gateway
  
  codec:
    max-in-memory-size: 10MB

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8080
          predicates:
            - Path=/api/credentials/**,/api/login

        - id: user-service
          uri: http://user-service:8080
          predicates:
            - Path=/api/users/**, /api/users

        - id: artist-service
          uri: http://artist-service:8080
          predicates:
            - Path=/api/artists/**, /api/artists

        - id: art-service
          uri: http://art-service:8080
          predicates:
            - Path=/api/art/**, /api/art

        - id: export-service
          uri: http://export-service:8080
          predicates:
            - Path=/api/export/**, /api/export

        - id: notification-service
          uri: http://notification-service:8080
          predicates:
            - Path=/api/notification/**, /api/notification

        - id: statistics-service
          uri: http://statistics-service:8080
          predicates:
            - Path=/api/statistics/**, /api/statistics

        - id: art-storage
          uri: http://minio:9000
          predicates:
            - Path=/media/art/**
          filters:
            - RewritePath=/media/art/(?<segment>.*), /art-bucket/${segment}

        - id: artist-storage
          uri: http://minio:9000
          predicates:
            - Path=/media/artist/**
          filters:
            - RewritePath=/media/artist/(?<segment>.*), /artist-bucket/${segment}

management:
  endpoints:
    web:
      exposure:
        include: health, info
